name: PullRequestTests

on:
  pull_request:
    branches: [ develop ]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 11 }
      - name: Run tests with jacoco
        run: ./gradlew jacocoTestReportDebug

  build-apk:
    name: Build develop artifact
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 11}
      - name: Build release APK
        run: ./gradlew assembleRelease
